### ISSUE TITLE
Clicking a Disabled Button resend previous signal

### ISSUE THREAD

**Issue by nickandwolf** [ceccopierangiolieugenio/pyTermTk#108]
I have a <PREV and NEXT> button setup and if we're at Step 1, then <PREV needs to be disabled. Once disabled, I clicked on it and it repeated the last function. So if that was the NEXT> connected function, it ran that. If it was a popup window button, it would pop up more windows.

Very interesting bug 😄

**Comment by ceccopierangiolieugenio** [comment]
it looks some strange behaviour, it could be related to the way the released button is forced if the widget change focus 
(i.e. if the button trigger a popup window)
Do you have an example that can expose it?

**Comment by nickandwolf** [comment]
https://gist.github.com/nickandwolf/24c346c043dd6e971899f734acf8a9f8

Alright so here's how to recreate it.
STEP1: Click [  BIO  ] or [🎲]
STEP2: Click the disabled <PREV

It will continue to cycle through random names as if it is calling the connected function.

(I couldn't reproduce it doing to the NEXT> function)

**Comment by ceccopierangiolieugenio** [comment]
interesting, I got it,
the disabled widget skip the input event (instead of processing with an empty function)
and this led the event to be forwarded to the active widget (in this case [  BIO  ] or [🎲])
There are many hardcoded exceptions in the way the different input are processed (i.e. the move event is sent to the focused widget also if the mouse is outside its boundaries),
I am not surprised about those edge cases.
I will fix it soon.
