### ISSUE TITLE
TTkString object has no attribute 'split'

### ISSUE THREAD

**Issue by gkzsolt** [ceccopierangiolieugenio/pyTermTk#21]
Hi,

It's fantastic, but I'd like to display simple text wrapping in a window. As long as I could find out, the _texedit_ widget (in texedit.py) is for that (?).
But it has a problem. On the demo, clicking on Layouts | Sources gives the error in the subject. Even after correcting it, there is another error popping up. 

Thanks,

**Comment by ceccopierangiolieugenio** [comment]
Hi, In those days I am working on the TextEdit widget,
At the moment it is able only to display text and not edit it.
The text wrapping is a feature I have not implemented yet but I will try to add it soon,
I think you are having this error because the library you installed is not up to dated, I recently added the split function, you can try to remove the installed library, the demo automatically pickup the library in the root path if it is not available on pip.
I will release the almost feature complete TextEdit in the next days.

**Comment by gkzsolt** [comment]
Thank you for the quick reply. Which is the library I should remove? I'll look up to the software in a week.
Otherwise it looks really good ;-)
All the best,
   Zsolt

**Comment by ceccopierangiolieugenio** [comment]
I was wondering if maybe you have installed in your system an old version of pyTermTk that does not have the split function,
Anyway, I just published the latest TextEdit, still there are some api missing but you can try it in the demo.
If you still have issues, please, paste here the error message and the command you are running,
Usually if you just clone the project and run:
`demo/demo.py`
you should not have any issues.

**Comment by gkzsolt** [comment]
I cloned the project. `python3 demo/demo.py` gives:
```
  File "demo/demo.py", line 236, in main
    demoShowcase(winTabbed1, border)
  File "demo/demo.py", line 153, in demoShowcase
    tabWidgets.addTab(demoTextEdit(),    " Text Edit ")
  File "/home/zkiss/apps/pyTermTk/demo/showcase/textedit.py", line 48, in demoTextEdit
    te.setReadOnly(False)
AttributeError: 'TTkTextEdit' object has no attribute 'setReadOnly'
```

**Comment by gkzsolt** [comment]
That works! You were right, I uninstalled pyTermTk installed previously with _pip_, cloned the repo and run `demo.py`.
Grazie!

**Comment by UltraStudioLTD** [comment]
@ceccopierangiolieugenio
Should this issue stay opened?

**Comment by gkzsolt** [comment]
No thanks, it is solved. Thank you!

**Comment by ceccopierangiolieugenio** [comment]
thanks
