### ISSUE TITLE
Integration with a TK Designer?

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#24]
Hello, first off, let me say, thanks for creating this project - it is very cool and looks very promising!

I am not particularly familiar with Tk design, so using something like [Tk Designer](https://github.com/ParthJadhav/Tkinter-Designer) is attractive to me. Is there any way it would work with pyTermTk? Forgive the n00b question. :-)

(p.s. I am evaluating pyTermTk's use for [one of my own projects](https://github.com/jeffwright13/pytest-fold))

**Comment by ceccopierangiolieugenio** [comment]
Actually I am not very familiar with TK as well, I just played a little bit in order to have an Idea about the best aproach in GUI api.
In the end my project is more similar to QT than tcl-tk or gtk, I would say that from tcl-tk I am just picking up the widgets initialization.
About having a tool to help the ui design I was thinking baout creating something similar to [QT Designer](https://doc.qt.io/qt-5/qtdesigner-manual.html), but in order to achieve it I need to perfect the drag and drop capabilities (missing at the moment).

**Comment by jeffwright13** [comment]
Sounds great! Keep us posted on your progress.
