### ISSUE TITLE
Exception when connecting signal to slot

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#37]
OK, what am I doing wrong here? I get en exception when this code runs and the `results_list.textClicked.connect` method is called. I believe my slot and signal APIs match (no parameters).

```
    @ttk.pyTTkSlot()
    def _results_list_callback() -> None:
        test_text = "Hi"

    def create_result_lists(self) -> None:
        for result in ("Errors", "Passes", "Failures", "Skipped", "Xfails", "Xpasses"):
            results_list = ttk.TTkList(
                parent=self.tab_widget,
                selectionMode=ttk.TTkK.MultiSelection,
            )

            results_list.textClicked.connect(self._results_list_callback)

            for key in eval(f"self.test_results.{result.lower()}.keys()"):
                results_list.addItem(key)

            self.tab_widget.addTab(results_list, f" {result} ")

```

Traceback:
<img width="1121" alt="Screen Shot 2022-03-27 at 9 06 13 AM" src="https://user-images.githubusercontent.com/4308435/160282811-5cddfe2f-b0b1-4a3f-82c8-333888761364.png">

**Comment by ceccopierangiolieugenio** [comment]
This is because the textClicked signal require a function that accept a string in input,
in the demo you can find an example:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/531bd9e46565c86a89e2f3a7ddb7acdcb74a3837/demo/demo.py#L201-L219

or in the list showcase:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/531bd9e46565c86a89e2f3a7ddb7acdcb74a3837/demo/showcase/list.py#L55-L66
