### ISSUE TITLE
How can I move the focus up or down on elements using the up/down arrows on the keyboard?

### ISSUE THREAD

**Issue by PopkovS** [ceccopierangiolieugenio/pyTermTk#43]
I've just started studing this library аnd i'm very impressed!
But i have some questions.
When run calculator from tutorial, i can't move focus up and down by arrows on the keyboard.
Is it even possible?

**Comment by ceccopierangiolieugenio** [comment]
At the moment the only way to switch focus in between the buttons is to use the "Tab" that is used by default.
I am trying to miic the same QT approach when I designed the behaviour and the API, I haven't check and I don't know if it is possible using QT to change focus from the buttons using the arrow keys, I'll try to figure it out and I will check if it is possible to include it.

**Comment by ceccopierangiolieugenio** [comment]
Just noticed that in qt (up,Down,Left,Right) just move the focus to the next/prev without considering the relative position of the widget, I can add those keys int he tab switching map.
I need to investigate if is is possible to proxy the focus switching logic in order to implement a proper keyboard mapping.
In my demo it is possible anyway to ad some extra logic in the main window to accept keyboard inputs and change the focus accordingly.
I haven't added it to keep it as simple as possible.

**Comment by ceccopierangiolieugenio** [comment]
Added in: https://github.com/ceccopierangiolieugenio/pyTermTk/pull/50/commits/8de37bca0b8f5c28ef74fb555e4fedc8ba43e1e6
