### ISSUE TITLE
[Question] General Question... Progress bar

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#78]
Hi there,

Do you have any plans to implement a progress bar witget? I'm trying to build one , thinking on event/signal, I was also looking at your demo graph... Any advice?

**Comment by castben** [comment]
Nevermind, I just saw Pull request where you already dealing with that... I'm setting this to close

**Comment by ceccopierangiolieugenio** [comment]
I was trying to check if I can push some changes to your pull request but I haven't figured it out yet, 
I am not sure if it is possible unless I fork your repo and raise a pull request on your branch so that you can push your on mine. 

About the progress bar, I am thinking about the proper way to have a LookAndFeel object that does not overcomplicate things that could be easily implemented adding some extra methods in the widget itself.

Another thing is that the "Paint" method is a special one and any callback there inside need to be carefully crafted to avoid any method/signal that may trigger an update() to avoid loops.
(i.e., passing the value to the callback instead of the bar object)

Anyway I have some ideas about, I think I will push something in the next days.

**Comment by castben** [comment]
Hi, no I did not did any pull request, I was looking around, and saw that pull request from @luchr  which implemented a progress bar and you and him were discussing how will be best way to do that.

So I did not wanted to bother you with something you already have in your radar. But thank you anyway for responding.

What I will do is implement what @luchr did in his example to have something working until the official one is being released.

**Comment by ceccopierangiolieugenio** [comment]
I apologise, I confused you with Luchr 😁.

Have a look at this, it is  a more updated version.
https://github.com/ceccopierangiolieugenio/pyTermTk/pull/76
be aware that I will change the properties from
**value_min**, **value_max**, **value**
to
setter:
```
setValue()
setMaximum()
setMinimum()
```
getter:
```
value()
maximum()
minimum()
```

**Comment by castben** [comment]
Excelent. I will use this one instead, thank you!
